# Generated by Django 3.1.1 on 2020-10-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20200927_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tests',
        ),
    ]
