@startuml
left to right direction
interface API as api
component Frontend as frontend
component Backend as backend
skinparam actorStyle awesome
:User: --> api: HTTP
:User: --> frontend: Browser
api --> backend

@enduml