@startuml
class Question {
    name: str
    description: str
}

class Category {
    name: str
}

class Difficulty {
    name: str
}

class Test {
    input: json
    expected: json
}

Test --|> Question: fk
Question --|> Category: fk
Question --|> Difficulty: fk
@enduml