# Generated by Django 3.1.2 on 2020-10-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='signature',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
