# Generated by Django 3.1.2 on 2020-10-16 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='test_cases',
            new_name='_test_cases',
        ),
    ]
